@startuml getjobs
actor Caller
entity API
collections Library

autonumber
header GetJobs
footer Page %page% of %lastpage%

title GetJobs: jobs found

Caller -> API: GetJobsRequest()
...
API -> API: process certificate
API -> Library: certificate.GetJobs()
Library -> API: jobs []*Job (non-empty slice)
API -> Caller: GetJobsResponse(jobs: jobs, error: nil)

newpage GetJobs: no jobs found
autonumber 1

Caller -> API: GetJobsRequest()
...
API -> API: process certificate
API -> Library: certificate.GetJobs()
Library -> API: jobs []*Job (empty slice)
API -> Caller: GetJobsResponse(jobs: jobs, error: nil)

newpage GetJobs: error getting jobs
autonumber 1

Caller -> API: GetJobsRequest()
...
API -> API: process certificate
API -> Library: certificate.GetJobs()
Library -> API: err ErrorJobList
API -> Caller: GetJobsResponse(jobs: nil, error: err)

@enduml