@startuml startjob
actor Caller
entity API
collections Library

autonumber
header StartJob
footer Page %page% of %lastpage%

title StartJob: successful request

Caller -> API: StartJobRequest(command:<command>)
...
API -> API: process certificate
API -> API: get command from StartJobRequest
API -> Library: NewJob(<certificate>, <command>)
Library -> API: job *Job
API -> Library: job.Start()
Library -> API: nil
API -> Caller: [OK] StartJobResponse(job: job)

newpage StartJob: error starting job
autonumber 1

Caller -> API: StartJobRequest(command:<command>)
...
API -> API: process certificate
API -> API: get command from StartJobRequest
API -> Library: NewJob(<certificate>, <command>)
Library -> API: job *Job
API -> Library: job.Start()
Library -> API: err ErrorJobStart
API -> Caller: [INTERNAL] StartJobResponse(job: nil)

@enduml