@startuml listjobs

actor TTY
entity STDOUT
entity STDERR
entity CLI
entity API

autonumber
header ListJobs
footer Page %page% of %lastpage%

title ListJobs: jobs found

TTY -> CLI: jb list
CLI -> API: GetJobsRequest()
...
API -> API: process mTLS
API -> API: get jobs
API -> CLI: GetJobsResponse(jobs: jobs, error: nil)
CLI -> STDOUT: Jobs found: jobs details
CLI -> TTY: exit(0)

newpage ListJobs: no jobs found
autonumber 1

TTY -> CLI: jb list
CLI -> API: GetJobsRequest()
...
API -> API: process mTLS
API -> API: get jobs
API -> CLI: GetJobsResponse(jobs: nil, error: nil)
CLI -> STDOUT: No jobs found
CLI -> TTY: exit(0)

newpage ListJobs: error listing jobs
autonumber 1

TTY -> CLI: jb list
CLI -> API: GetJobsRequest()
...
API -> API: process mTLS
API -> API: get jobs
API -> CLI: GetJobsResponse(jobs: nil, error: err)
CLI -> STDERR: Error listing jobs: err
CLI -> TTY: exit(1)

@enduml