@startuml logjob

actor TTY
entity STDOUT
entity STDERR
entity CLI
entity API

autonumber
header LogJob
footer Page %page% of %lastpage%

title LogJob: default request

TTY -> CLI: jb log <job id>
CLI -> API: GetJobLogRequest(job_id:<job id>)
...
API -> API: process mTLS
API -> API: get job ID from GetJobLogRequest
API -> API: get job log
API -> CLI: GetJobLogResponse(log: log, error: nil)
CLI -> STDOUT: Display log snapshot
CLI -> TTY: exit(0)

newpage LogJob: tailing the log
autonumber 1

TTY -> CLI: jb log -f <job id>
CLI -> API: GetJobLogRequest(job_id:<job id>)
...
API -> API: process mTLS
API -> API: get job ID from GetJobLogRequest
API -> API: get job log
API -> CLI: GetJobLogResponse(log: log, error: nil)
CLI -> STDOUT: Display log lines as they are written
...
TTY -> CLI: ctr+c
CLI -> TTY: exit(0)

newpage LogJob: error getting job log
autonumber 1

TTY -> CLI: jb log <job id>
CLI -> API: GetJobLogRequest(job_id:<job id>)
...
API -> API: process mTLS
API -> API: get job ID from GetJobLogRequest
API -> API: get job log
API -> CLI: GetJobLogResponse(log: nil, error: err)
CLI -> STDERR: Error getting job log: err
CLI -> TTY: exit(1)

@enduml